name: beta push onbloc-tx-indexer

on:
  push:
    branches:
      - beta
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
jobs:
  main_tx_indexer:
    name: Run tx-indexer app
    uses: ./.github/workflows/app_template.yml
    with:
      app-name: 'tx-indexer'
      env: 'beta'
      region: 'us-east-1'
    secrets:
      AWS_IAM_OIDC: ${{ secrets.AWS_IAM_OIDC }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
