on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      env:
        required: true
        type: string
    secrets:
      PAT_TOKEN:
        required: true

permissions:
  contents: write
  id-token: write
jobs:
  helm_chart_push:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo gnoswap-helm-chart
        run: |
          echo ${{ secrets.PAT_TOKEN }}
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/gnoswap-labs/gnoswap-helm-chart.git gnoswap-helm-chart

      - name: Make changes to gnoswap-helm-chart Repo
        run: |
          set -e
          cd gnoswap-helm-chart/

          DEPLOY="deploy-${{ github.run_id }}-${{ inputs.app-name }}-${{ inputs.env }}"
          TARGET="${{ inputs.env }}-${{ inputs.app-name }}"

          if git ls-remote --exit-code --heads origin "$TARGET"; then
            git checkout -b "$DEPLOY" "origin/$TARGET"
          else
            git checkout -b "$TARGET" "origin/${{ inputs.env }}"
            git push -u origin "$TARGET"
            git checkout -b "$DEPLOY" "origin/$TARGET"
          fi

          cd ${{ inputs.app-name }}
          sed -i "s/^\(\s*tag\s*:\s*\).*/\1'${{ inputs.env }}-${{ github.sha }}'/" values-${{ inputs.env }}.yaml

      - name: Commit and push changes to helm repository
        run: |
          set -e
          cd gnoswap-helm-chart/

          DEPLOY="deploy-${{ github.run_id }}-${{ inputs.app-name }}-${{ inputs.env }}"
          TARGET="${{ inputs.env }}-${{ inputs.app-name }}"

          git config --global user.email "gnoswap@onbloc.xyz"
          git config --global user.name "onbloc"

          git add .
          git commit -m "chore: bump $TARGET chart to ${{ github.sha }}"

          git push origin "$DEPLOY"

          git checkout "$TARGET"
          git pull --rebase origin "$DEPLOY" || git rebase --abort
          git push origin "$TARGET"

          git branch -d "$DEPLOY"
          git push origin --delete "$DEPLOY"

          echo "  ____                     _ "
          echo " |  _ \  ___  _ __   ___  | |"
          echo " | | | |/ _ \| '_ \ / _ \ | |"
          echo " | |_| | (_) | | | |  __/ |_|"
          echo " |____/ \___/|_| |_|\___| (_)"